import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { build as bundle } from "esbuild";

const site = {
  url: "https://masethecreative.co.uk",
  instagram: "https://instagram.com/masethecreative",
  name: "Mase the Creative",
};

const projects = [
  { slug: "fourwards", title: "Fourwards", client: "Fourwards Restaurant", industry: "Hospitality", type: "Hospitality · Monthly content", category: "hospitality", image: "/media/fourwards/hero.jpg", alt: "A table of freshly prepared dishes at Fourwards Restaurant.", summary: "An ongoing library of photography and social-first films built around the food, people and personality of an independent restaurant.", challenge: "A busy restaurant never has just one story to tell. The content needed to keep pace with new dishes, offers, events and the people behind the service—without every post feeling like another advert.", approach: "Build recurring formats around the real rhythm of the business: preparation in the kitchen, finished plates, team personalities, useful chef-led ideas and the atmosphere customers actually experience.", deliverables: "Monthly content · Photography · Reels · Campaign films", gallery: ["/media/fourwards/preparation.jpg", "/media/fourwards/pancakes.jpg", "/media/fourwards/brunch.jpg", "/media/fourwards/exterior.jpg", "/media/fourwards/outdoor-dining.jpg", "/media/fourwards/service.jpg", "/media/fourwards/drinks.jpg"], videos: [{src:"/media/fourwards/cinematic-prep.mp4",poster:"/media/fourwards/poster-prep.jpg",label:"Cinematic kitchen preparation",format:"landscape"},{src:"/media/fourwards/at-home-teaser.mp4",poster:"/media/fourwards/poster-home.jpg",label:"Fourwards at Home campaign teaser",format:"landscape"}] },
  { slug: "gopsall-hall-farm", title: "Gopsall Hall Farm", client: "Gopsall Hall Farm", industry: "Hospitality & events", type: "Hospitality · Brand storytelling", category: "hospitality", image: "/media/gopsall/hero.jpg", alt: "A finished accommodation interior at Gopsall Hall Farm.", summary: "Photography and films documenting the accommodation, venue, events and people behind a rural business as it develops.", challenge: "The business spans accommodation, events, hospitality and an evolving site. The content needed to explain what was available now while also showing the care, progress and ambition behind what was being built.", approach: "Treat the development itself as part of the story. Polished interiors and guest experiences sit alongside opening events, countryside views and honest behind-the-scenes progress, giving the business a body of content with real continuity.", deliverables: "Photography · Property films · Social content · Event coverage", gallery: ["/media/gopsall/view.jpg", "/media/gopsall/twin-room.jpg", "/media/gopsall/opening.jpg", "/media/gopsall/venue.jpg", "/media/gopsall/glamping.jpg", "/media/gopsall/pod.jpg", "/media/gopsall/interior.jpg", "/media/gopsall/development.jpg"], videos: [{src:"/media/gopsall/introduction.mp4",poster:"/media/gopsall/poster-intro.jpg",label:"Gopsall accommodation introduction",format:"portrait"},{src:"/media/gopsall/weekend-away.mp4",poster:"/media/gopsall/poster-weekend.jpg",label:"Weekend away social film",format:"portrait"}] },
  { slug: "people-with-presence", title: "People with presence", type: "People · Photography", category: "people", image: "/media/portrait-sun.webp", alt: "Portrait of a woman outdoors beneath a bright, cloud-filled sky.", summary: "Natural, character-led portraits that feel considered without feeling staged.", gallery: ["/media/woman-red.webp", "/media/man-dusk.webp"] },
  { slug: "hospitality-in-motion", title: "Hospitality in motion", type: "Hospitality · Social content", category: "hospitality", image: "/media/chef-doorway.webp", alt: "A chef in an apron smiling from the doorway of a restaurant.", summary: "Food, people and atmosphere shaped into a visual story customers can almost taste.", gallery: ["/media/food.webp", "/media/chef-prep.webp", "/media/restaurant.webp"] },
  { slug: "after-dark", title: "After dark", type: "Hospitality · Photography", category: "hospitality", image: "/media/cocktail.webp", alt: "A cocktail served in a coupe glass with a cherry garnish.", summary: "A warm, cinematic study of service, detail and the mood of an evening out.", gallery: ["/media/table-setting.webp", "/media/restaurant.webp"] },
  { slug: "story-in-frame", title: "A story in every frame", type: "Brand film · Campaign", category: "film", image: "/media/vintage-car.webp", alt: "A man in vintage formalwear standing beside a classic black car.", summary: "Narrative-led campaign imagery built to stop the scroll and leave a lasting impression.", gallery: ["/media/top-hat.webp", "/media/field-sunset.webp", "/media/christmas-card.webp"] },
];

const services = [
  ["01", "Monthly social content", "A reliable stream of photography, short-form video and ideas—planned, shot and edited without adding another job to your week."],
  ["02", "Photography", "Commercial, hospitality, people, product, event and lifestyle photography with an editorial eye."],
  ["03", "Video production", "Brand films, interviews, behind-the-scenes stories, event coverage and launch content made for every screen."],
  ["04", "Content strategy", "Repeatable formats, strong hooks and a practical plan for what to make, where to post and why it matters."],
  ["05", "Reels & TikTok", "Vertical films designed around attention, personality and stories people genuinely want to finish."],
  ["06", "Campaigns & launches", "Focused creative support for new menus, products, locations, events, seasons and big announcements."],
];

const icon = `<svg viewBox="0 0 22 22" aria-hidden="true"><path d="M4 11h13M12 5l6 6-6 6"/></svg>`;
const arrow = (label, href, cls = "text-link") => `<a class="${cls}" href="${href}"><span>${label}</span>${icon}</a>`;
const picture = (src, alt, cls = "", { priority = false, width, height } = {}) => `<img class="${cls}" src="${src}" alt="${alt}" loading="${priority ? "eager" : "lazy"}"${priority ? ' fetchpriority="high"' : ""}${width ? ` width="${width}"` : ""}${height ? ` height="${height}"` : ""} decoding="async">`;

function shell({ title, description, path, body, theme = "dark", schema = "" }) {
  const canonical = `${site.url}${path === "/" ? "" : path}`;
  const nav = [["Work", "/work/"], ["Clients", "/clients/"], ["Services", "/services/"], ["Content Guidance", "/content-guidance/"], ["About", "/about/"]];
  return `<!doctype html>
<html lang="en-GB" data-theme="${theme}">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${title} — Mase the Creative</title>
  <meta name="description" content="${description}"><link rel="canonical" href="${canonical}">
  <meta property="og:type" content="website"><meta property="og:site_name" content="Mase the Creative"><meta property="og:title" content="${title} — Mase the Creative"><meta property="og:description" content="${description}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${site.url}/media/chef-doorway.webp">
  <meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#0b0b0a">
  <link rel="icon" href="/mase-favicon.jpg" type="image/jpeg"><link rel="stylesheet" href="/styles.css">
  <script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"ProfessionalService",name:site.name,url:site.url,sameAs:[site.instagram],founder:{"@type":"Person",name:"Mason Osborne"},areaServed:"United Kingdom"})}</script>${schema ? `
  <script type="application/ld+json">${JSON.stringify(schema)}</script>` : ""}
</head>
<body>
  <a class="skip" href="#main">Skip to content</a>
  <header class="site-header" data-header>
    <a class="brand" href="/" aria-label="Mase the Creative home"><img class="brand-logo" src="/brand/mase-logo.png" alt="Mase the Creative"></a>
    <nav class="desktop-nav" aria-label="Primary">${nav.map(([n,h]) => `<a href="${h}"${path.startsWith(h.replace(/\/$/,"")) ? ` aria-current="page"` : ""}>${n}</a>`).join("")}<a class="nav-login" href="/portal/">Client Login</a><a class="nav-cta" href="/contact/">Start a project</a></nav>
    <button class="menu-button" type="button" aria-expanded="false" aria-controls="mobile-menu"><span>Menu</span><i></i><i></i></button>
  </header>
  <div class="mobile-menu" id="mobile-menu" aria-hidden="true"><nav aria-label="Mobile">${nav.map(([n,h],i)=>`<a href="${h}"><small>0${i+1}</small>${n}</a>`).join("")}<a href="/portal/"><small>0${nav.length+1}</small>Client Login</a><a href="/contact/"><small>0${nav.length+2}</small>Start a project</a></nav><a href="${site.instagram}">Instagram ↗</a></div>
  <main id="main">${body}</main>
  <footer class="site-footer">
    <div><p class="eyebrow">Ready when you are</p><h2>Make something<br><em>worth watching.</em></h2>${arrow("Start a project", "/contact/", "button light")}</div>
    <div class="footer-row"><a class="brand footer-brand" href="/" aria-label="Mase the Creative home"><img class="brand-logo" src="/brand/mase-logo.png" alt="Mase the Creative"></a><nav>${nav.map(([n,h])=>`<a href="${h}">${n}</a>`).join("")}<a href="/contact/">Contact</a></nav><div><a href="${site.instagram}">Instagram ↗</a><p>Trading as Edge Media Creative</p></div></div>
    <div class="footer-base"><span>© ${new Date().getFullYear()} Mase the Creative</span><span>Photography · Film · Social</span></div>
  </footer>
  <aside class="chatbot" data-chatbot>
    <button class="chatbot-launch" type="button" aria-label="Ask Mase" aria-expanded="false" aria-controls="mase-chat"><span class="chatbot-pulse"></span><span>Ask Mase</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 6.5h14v9H9l-4 3v-12Z"/></svg></button>
    <section class="chatbot-panel" id="mase-chat" aria-label="Ask Mase assistant" aria-hidden="true">
      <header class="chatbot-header"><div><span class="chatbot-avatar">M</span><p><strong>Ask Mase</strong><small>Business assistant · replies instantly</small></p></div><button type="button" class="chatbot-close" aria-label="Close assistant">×</button></header>
      <div class="chatbot-messages" role="log" aria-live="polite" aria-relevant="additions"><div class="chat-message assistant"><p>Hi — I can answer questions about Mase the Creative or help shape your enquiry.</p><p>What are you trying to achieve?</p></div></div>
      <div class="chatbot-quick" aria-label="Suggested replies"><button type="button">I need regular content</button><button type="button">I have a one-off project</button><button type="button">What do you offer?</button></div>
      <form class="chatbot-form"><label class="sr-only" for="chatbot-input">Message</label><textarea id="chatbot-input" name="message" rows="1" maxlength="1200" placeholder="Type your message…" required></textarea><button type="submit" aria-label="Send message">${icon}</button></form>
      <p class="chatbot-disclosure">AI assistant using verified Mase the Creative information. It cannot confirm prices or availability.</p>
    </section>
  </aside>
  <div class="cursor-dot" aria-hidden="true"></div><script src="/main.js" defer></script><script src="/chatbot.js" defer></script>
</body></html>`;
}

function projectCard(p, i) { return `<article class="project-card reveal" data-category="${p.category}"><a href="/work/${p.slug}/"><div class="project-media">${picture(p.image,p.alt)}<span class="project-index">0${i+1}</span><span class="view-pill">View project ${icon}</span></div><div class="project-meta"><h3>${p.title}</h3><p>${p.type}</p></div></a></article>`; }

const home = shell({title:"Content made to be noticed",description:"Photography, film and social content for businesses ready to get noticed.",path:"/",body:`
<section class="hero">
  <div class="hero-bg">${picture("/media/chef-doorway.webp","A chef smiling in the doorway of a restaurant.","hero-image",{ priority: true, width: 1500, height: 2250 })}</div><div class="hero-shade"></div>
  <div class="hero-copy"><p class="eyebrow reveal">Photography · Film · Social</p><h1><span class="reveal">Your business</span><span class="reveal"><em>deserves</em> to be seen.</span></h1><div class="hero-bottom reveal"><p>Content made for the way people discover businesses now.</p>${arrow("Explore the work","/work/","button light")}</div></div>
  <div class="scroll-note">Scroll to discover <span>↓</span></div>
</section>
<section class="manifesto section-pad"><p class="eyebrow reveal">The feed has changed</p><h2 class="statement reveal">You are no longer posting<br>only to <span>your followers.</span></h2><div class="manifesto-grid"><p class="lead reveal">Social media is becoming <em>interest media.</em></p><div class="reveal"><p>The right piece of content can reach the right person before they have ever heard of your business. Platforms find audiences through interest, behaviour and relevance—not just a follower count.</p><p>That creates a bigger opening for businesses with something real to show.</p>${arrow("Why content matters","/services/")}</div></div></section>
<section class="guidance-promo section-pad"><div class="guidance-promo__heading reveal"><p class="eyebrow">New · Monthly content guidance</p><h2>Want to make the content <em>yourself?</em></h2></div><div class="guidance-promo__copy reveal"><p>Content Direction by Mase helps you choose the right kit, build a workable process and plan content your business can keep producing.</p><p class="availability-note">Pricing coming soon</p>${arrow("Explore Content Direction","/content-guidance/","button light")}</div></section>
<section class="selected-work section-pad"><div class="section-head reveal"><div><p class="eyebrow">Selected work</p><h2>Proof, not promises.</h2></div>${arrow("View every project","/work/")}</div><div class="project-grid">${projects.map(projectCard).join("")}</div></section>
<section class="attention section-pad"><div class="attention-sticky"><p class="eyebrow">Built for attention</p><h2>Good content earns<br>a second look.</h2></div><div class="attention-list">${[["01","Familiarity","Show up consistently enough to become recognisable."],["02","Trust","Let people see the faces, craft and thinking behind the business."],["03","Consideration","Give a future customer a reason to remember you when it matters."],["04","Momentum","Build a useful library for social, your website and every campaign after it."]].map(x=>`<article class="reveal"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("")}</div></section>
<section class="services-preview section-pad"><div class="section-head reveal"><div><p class="eyebrow">What I do</p><h2>One creative partner.<br>Every useful format.</h2></div><p>From the first idea to the final export, the work stays connected to what your business actually needs.</p></div><div class="service-lines">${services.slice(0,5).map(s=>`<a href="/services/" class="reveal"><span>${s[0]}</span><h3>${s[1]}</h3>${icon}</a>`).join("")}</div></section>
<section class="about-split"><div class="about-photo reveal">${picture("/media/mason.webp","Mason Osborne, founder of Mase the Creative.")}</div><div class="about-copy section-pad reveal"><p class="eyebrow">Behind the camera</p><h2>Creative instinct.<br><em>Business sense.</em></h2><p>I’m Mason—the person planning, shooting and editing the work. A background in retail and business means I understand that content cannot just look good. It has to be useful, clear and worth the time it takes to make.</p>${arrow("Meet Mason","/about/")}</div></section>`});

const work = shell({title:"Selected work",description:"A selection of photography, hospitality, people and campaign work by Mase the Creative.",path:"/work/",theme:"light",body:`<section class="page-hero light"><p class="eyebrow reveal">Selected work · 2026</p><h1 class="reveal">Made to be<br><em>remembered.</em></h1><p class="page-intro reveal">A selection of people, places, products and moments—captured with enough character to stop somebody mid-scroll.</p></section><section class="work-page section-pad"><div class="filters reveal" aria-label="Filter work"><button class="active" data-filter="all">All</button><button data-filter="hospitality">Hospitality</button><button data-filter="people">People</button><button data-filter="film">Film & campaign</button></div><div class="project-grid work-grid">${projects.map(projectCard).join("")}</div><div class="gallery-strip reveal">${["/media/project-01.webp","/media/project-02.webp","/media/project-03.webp"].map((x,i)=>picture(x,`Additional portfolio image ${i+1}`)).join("")}</div></section>`});

const servicesPage = shell({title:"Services",description:"Monthly social content, photography, video production and content strategy for modern businesses.",path:"/services/",body:`<section class="page-hero"><p class="eyebrow reveal">Services</p><h1 class="reveal">Everything you need<br>to <em>show up well.</em></h1><p class="page-intro reveal">Not a menu of disconnected deliverables. A joined-up creative process built around what your business needs people to notice.</p></section><section class="service-detail section-pad">${services.map(s=>`<article class="reveal"><span>${s[0]}</span><h2>${s[1]}</h2><p>${s[2]}</p>${arrow("Discuss this service","/contact/")}</article>`).join("")}</section><section class="process section-pad"><p class="eyebrow reveal">A simple process</p><h2 class="reveal">Less friction.<br>Better work.</h2><ol>${["Understand the business","Develop the ideas","Plan the shoot","Create the content","Edit and deliver","Review and improve"].map((x,i)=>`<li class="reveal"><span>0${i+1}</span><p>${x}</p></li>`).join("")}</ol></section>`});

const guidanceAreas = [
  ["01", "Gear", "Choose cameras, phones, lighting, audio and supporting kit around the work you actually need to make—not somebody else’s shopping list."],
  ["02", "Photography", "Get clearer on light, framing and simple repeatable setups so your everyday business photographs feel more intentional."],
  ["03", "Video", "Plan and capture useful footage with steadier pictures, clearer sound and a purpose before you press record."],
  ["04", "Editing", "Select sensible photo and video software, then shape a workflow that takes you from files on a device to a finished export."],
  ["05", "Posters & graphics", "Choose suitable design tools and make clearer promotional graphics with better hierarchy, sizing and consistency."],
];

const guidanceFaq = [
  ["Do I need content-creation experience?", "No. The membership is for beginners as well as people who have already started and want a clearer process. Guidance should meet you where you are without talking down to you."],
  ["What if I already own equipment?", "Start there. The aim is to make better decisions with what you have, identify genuine gaps and avoid replacing useful kit for the sake of it."],
  ["Will every recommendation be expensive?", "No. Recommendations should reflect your budget, business needs and the content you need to produce. Sometimes the most useful change is how you use your current setup."],
  ["Which editing or design software will you recommend?", "That depends on the work you make, the device you use, your experience and your budget. The point is to choose suitable software—not push everybody towards the same app."],
  ["Can I cancel the membership?", "Cancellation and payment terms are still being finalised. They will be made clear before anybody subscribes; you can register your interest now and ask Mason for the confirmed details when they are ready."],
];

const contentGuidance = shell({
  title:"Content Direction by Mase",
  description:"Practical monthly guidance for small-business owners who want to choose the right content kit, build a workable process and create better content themselves.",
  path:"/content-guidance/",
  schema:{"@context":"https://schema.org","@graph":[{"@type":"Service",name:"Content Direction by Mase",serviceType:"Monthly content guidance membership",url:`${site.url}/content-guidance/`,description:"Practical monthly guidance for small-business owners who want to choose the right content kit, build a workable process and create better content themselves.",provider:{"@type":"ProfessionalService",name:site.name,url:site.url},areaServed:"United Kingdom"},{"@type":"FAQPage",mainEntity:guidanceFaq.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))}]},
  body:`
<section class="guidance-hero">
  <div class="guidance-hero__copy"><p class="eyebrow reveal">Content Direction by Mase · Monthly membership</p><h1 class="reveal">Make better content for your business—<em>with someone to guide you.</em></h1><p class="guidance-lead reveal">You do not need to buy everything or learn every editing program. You need the right setup, a workable process and honest guidance about what will make the biggest difference.</p><div class="guidance-actions reveal">${arrow("Register your interest","/contact/","button light")}${arrow("See how it works","#how-it-works")}</div><p class="availability-note reveal">Pricing coming soon</p></div>
  <div class="guidance-hero__panel reveal" aria-label="The three outcomes of Content Direction"><span>01 · Choose well</span><span>02 · Make with purpose</span><span>03 · Improve each month</span></div>
</section>
<section class="guidance-intro section-pad"><div class="reveal"><p class="eyebrow">Who it is for</p><h2>A practical route into creating your own business content.</h2></div><div class="reveal"><p>Content Direction is for small-business owners and aspiring content creators who want to make more of their own photography, video and graphics—but want experienced direction before spending money or losing hours to trial and error.</p><p>It is not a one-off course and it is not a substitute for professional production. It is ongoing guidance for the content your business can sensibly create in-house, with a clear route to Mase when a brief needs a full creative production.</p><div class="audience-tags" aria-label="Suitable audiences"><span>Small-business owners</span><span>Sole traders</span><span>In-house beginners</span><span>Aspiring creators</span></div></div></section>
<section class="right-place section-pad"><div class="section-head reveal"><div><p class="eyebrow">You might be in the right place if…</p><h2>The problem is not effort.<br>It is knowing what matters.</h2></div></div><div class="problem-grid">${[
  "You are not sure whether your phone is enough or a camera would genuinely help.",
  "Every gear video adds something else to a shopping list you do not trust.",
  "You can capture content, but editing it takes too long or feels inconsistent.",
  "You only decide what to post when the business is already busy.",
  "You have tried several apps and still do not have a simple workflow.",
  "You want your content to improve without pretending every job should be done in-house.",
].map((x,i)=>`<article class="reveal"><span>0${i+1}</span><p>${x}</p></article>`).join("")}</div></section>
<section class="membership-value section-pad"><div class="membership-value__intro reveal"><p class="eyebrow">What the membership gives you</p><h2>Direction you can put to work.</h2><p>The focus stays on practical decisions for your business—not collecting more theory.</p></div><div class="membership-value__list">${[
  ["01","Better buying decisions","Guidance on cameras, phones, lighting, audio and supporting gear based on your real needs and budget."],
  ["02","Sensible software choices","Help choosing photo, video and graphic-design software that fits the way you work."],
  ["03","A workable production process","A clearer route from planning and capture through to editing, exporting and using the finished content."],
  ["04","Useful monthly direction","Help thinking through what your business should make next, so content is connected to real priorities."],
  ["05","More consistent output","Practical guidance on improving quality without making the process too complicated to repeat."],
  ["06","Honest production advice","Clarity on what you can create well yourself and when professional photography or film would earn its place."],
].map(x=>`<article class="reveal"><span>${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join("")}</div></section>
<section class="guidance-areas section-pad"><div class="section-head reveal"><div><p class="eyebrow">Guidance areas</p><h2>From the first purchase<br>to the final export.</h2></div><p>Advice stays grounded in the content your business actually needs to make.</p></div><div class="guidance-area-list">${guidanceAreas.map(x=>`<article class="reveal"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("")}</div></section>
<section class="monthly-model section-pad" id="how-it-works"><div class="monthly-model__heading reveal"><p class="eyebrow">Why monthly</p><h2>Your content needs will move.<br>Your guidance should too.</h2><p>This is ongoing practical support, not a library of lessons to finish once and forget.</p></div><ol>${[
  ["Start with where you are","Your experience, existing equipment, budget and business goals give the guidance its context."],
  ["Focus on the next useful improvement","Work on the decisions that matter now instead of trying to master every tool and format at once."],
  ["Keep the process relevant","As your content, confidence and business priorities change, the direction can change with them."],
].map((x,i)=>`<li class="reveal"><span>0${i+1}</span><h3>${x[0]}</h3><p>${x[1]}</p></li>`).join("")}</ol><p class="model-note reveal">The exact membership format, payment and subscription details are being finalised. Pricing and terms will be shared before you are asked to subscribe.</p></section>
<section class="make-or-hire section-pad"><div class="section-head reveal"><div><p class="eyebrow">Two useful ways to work</p><h2>Make it yourself.<br>Bring in Mase when it counts.</h2></div><p>Good content does not have to come from one route. Choose the level of support the brief deserves.</p></div><div class="choice-grid"><article class="choice-card reveal"><p class="eyebrow">Create it yourself · With guidance</p><h3>Best for regular, everyday content.</h3><p>Choose Content Direction when you want to build your own skills, make smart use of a realistic kit budget and create repeatable content inside the business.</p><ul><li>Day-to-day social content</li><li>Simple product, people and behind-the-scenes updates</li><li>Building confidence and a consistent process</li></ul>${arrow("Register your interest","/contact/")}</article><article class="choice-card choice-card--pro reveal"><p class="eyebrow">Professional production · By Mase</p><h3>Best when the finish and the moment carry more weight.</h3><p>Bring in Mase for higher-quality production, campaigns, launches or ongoing creative support when the business needs stronger ideas, specialist execution or time back.</p><ul><li>Campaigns, launches and important moments</li><li>Polished photography and film</li><li>Ongoing monthly content produced for you</li></ul>${arrow("Explore professional services","/services/")}</article></div><p class="choice-note reveal">The two can work together: keep everyday content moving in-house, then use professional production to raise the level when the opportunity calls for it.</p></section>
<section class="guidance-faq section-pad"><div class="guidance-faq__heading reveal"><p class="eyebrow">Frequently asked questions</p><h2>Straight answers,<br>before you start.</h2></div><div class="faq-list">${guidanceFaq.map(([question,answer])=>`<details class="reveal"><summary><span>${question}</span><i aria-hidden="true"></i></summary><p>${answer}</p></details>`).join("")}</div></section>
<section class="guidance-cta section-pad"><div class="reveal"><p class="eyebrow">Content Direction by Mase</p><h2>Ready to make your next piece of content a better one?</h2></div><div class="reveal"><p>Register your interest while the membership details are being finalised. Tell Mason what you make, what is getting in the way and where you would value some honest guidance.</p><p class="availability-note">Pricing coming soon</p>${arrow("Register your interest","/contact/","button light")}</div></section>`
});

const clients = shell({title:"Clients",description:"Creative support for hospitality, retail, automotive, professional services, events and lifestyle businesses.",path:"/clients/",theme:"light",body:`<section class="page-hero light"><p class="eyebrow reveal">Clients & collaborations</p><h1 class="reveal">Good work starts<br>with <em>knowing the business.</em></h1><p class="page-intro reveal">Mase the Creative works across hospitality, retail, automotive, professional services, events and lifestyle—adapting the format while keeping the story human.</p></section><section class="client-featured section-pad"><div class="section-head reveal"><div><p class="eyebrow">Featured relationships</p><h2>Built around the business.</h2></div><p>Photography and films made with enough continuity to show the people, place and work—not just one polished moment.</p></div><div class="project-grid">${projects.slice(0,2).map(projectCard).join("")}</div></section><section class="industry-list section-pad">${[["01","Hospitality","Food, atmosphere, teams and the reasons people choose to visit."],["02","Retail","Products with context, character and a point of view."],["03","Automotive & engineering","Craft, detail and capability captured with energy."],["04","Professional services","Clear, human content that puts expertise into view."],["05","Events & lifestyle","Real moments, thoughtful coverage and assets that keep working afterwards."]].map(x=>`<article class="reveal"><span>${x[0]}</span><h2>${x[1]}</h2><p>${x[2]}</p></article>`).join("")}</section><section class="relationship section-pad"><div class="reveal"><p class="eyebrow">Ongoing</p><h2>Keep showing up.</h2><p>Monthly content gives your business a consistent visual language and a useful bank of new material—without starting from zero every time you post.</p></div><div class="reveal"><p class="eyebrow">One-off</p><h2>Make the moment count.</h2><p>A focused shoot for a launch, campaign, event, new menu or story that needs to land properly.</p></div></section>`});

const about = shell({title:"About Mason",description:"Meet Mason Osborne, the photographer, filmmaker and creative partner behind Mase the Creative.",path:"/about/",body:`<section class="page-hero about-hero"><div><p class="eyebrow reveal">About Mason</p><h1 class="reveal">One person.<br><em>Fully invested.</em></h1><p class="page-intro reveal">No layers of account management. The person you speak to is the person thinking, planning, shooting and editing.</p></div>${picture("/media/mason.webp","Mason Osborne, founder of Mase the Creative.","reveal")}</section><section class="about-story section-pad"><div><p class="eyebrow reveal">The short version</p><h2 class="reveal">I make businesses look as good online as they are in real life.</h2></div><div class="story-copy reveal"><p>I’m Mason, the person behind Mase the Creative—a one-person production company making photography, films and social content for businesses with something worth showing.</p><p>My background spans retail, running a business, social media, photography and filmmaking. That mix matters. I know the creative has to earn attention, but I also know it has to fit the reality of a working business.</p><p>I keep the process direct: understand what makes the business interesting, find the idea, then turn up and make the work. No twelve-meeting agency theatre.</p></div></section><section class="beliefs section-pad"><p class="eyebrow reveal">The approach</p>${[["01","Useful beats ornamental.","Looking good is the start. Every shoot should give the business material it can actually use."],["02","Personality is an advantage.","The people, details and oddities behind a business are usually what make it memorable."],["03","Consistency compounds.","One strong film helps. A clear body of work, built over time, changes how a business is seen."]].map(x=>`<article class="reveal"><span>${x[0]}</span><h2>${x[1]}</h2><p>${x[2]}</p></article>`).join("")}</section>`});

const contact = shell({title:"Start a project",description:"Tell Mase the Creative about your photography, film, social content or content guidance enquiry.",path:"/contact/",body:`<section class="contact-page"><div class="contact-intro"><p class="eyebrow reveal">Start a project</p><h1 class="reveal">Let’s make<br>something <em>useful.</em></h1><p class="reveal">Tell me what you are building, launching or trying to get noticed. A rough idea is plenty.</p><div class="contact-social reveal"><span>Prefer a direct message?</span><a href="${site.instagram}">Instagram ↗</a></div></div><form class="project-form" novalidate><div class="field-row"><label><span>Your name *</span><input name="name" autocomplete="name" required></label><label><span>Business name *</span><input name="business" autocomplete="organization" required></label></div><div class="field-row"><label><span>Email *</span><input type="email" name="email" autocomplete="email" required></label><label><span>Phone <small>optional</small></span><input type="tel" name="phone" autocomplete="tel"></label></div><label><span>What do you need? *</span><select name="project" required><option value="">Choose a project type</option><option>Content Direction membership</option><option>Monthly social content</option><option>Photography</option><option>Video production</option><option>Event coverage</option><option>Campaign or launch</option><option>One-off content day</option><option>Something else</option></select></label><div class="field-row"><label><span>Approximate budget *</span><select name="budget" required><option value="">Choose a range</option><option>Under £1,000</option><option>£1,000–£2,500</option><option>£2,500–£5,000</option><option>£5,000+</option><option>Not sure yet</option></select></label><label><span>Preferred start</span><input type="date" name="start"></label></div><label><span>Tell me about it *</span><textarea name="message" rows="5" required placeholder="What are you working on, and what would a good outcome look like?"></textarea></label><label class="honeypot" aria-hidden="true">Company website<input name="company_website" tabindex="-1" autocomplete="off"></label><button class="button light submit-button" type="submit"><span>Prepare enquiry</span>${icon}</button><p class="form-note">Your details stay on this device. Preparing the enquiry copies it so you can send it directly.</p><div class="form-status" role="status" aria-live="polite"></div></form></section>`});

function caseStudy(p) { const videos = p.videos?.length ? `<section class="case-films section-pad"><div class="section-head reveal"><div><p class="eyebrow">Selected films</p><h2>Made to move.</h2></div><p>Short-form edits built for attention, personality and the way customers discover businesses now.</p></div><div class="case-film-grid">${p.videos.map(v=>`<figure class="reveal"><video class="${v.format || "portrait"}" controls playsinline preload="metadata" poster="${v.poster}" aria-label="${v.label}"><source src="${v.src}" type="video/mp4">Your browser does not support embedded video.</video><figcaption>${v.label}</figcaption></figure>`).join("")}</div></section>` : ""; return shell({title:p.title,description:p.summary,path:`/work/${p.slug}/`,body:`<article class="case-study"><header class="case-hero"><div><p class="eyebrow reveal">${p.type}</p><h1 class="reveal">${p.title}</h1><p class="reveal">${p.summary}</p></div>${picture(p.image,p.alt,"reveal")}</header><section class="case-overview section-pad"><div><p class="eyebrow">The opportunity</p><h2>${p.client ? "Show the whole business.<br>Not just the polished bit." : "Start with the feeling.<br>Build every frame around it."}</h2></div><div><p>${p.challenge || "The strongest content does more than document what happened. It gives the viewer a reason to stay, notice a detail and understand the character behind the business."}</p>${p.approach ? `<p>${p.approach}</p>` : ""}<dl><div><dt>Client</dt><dd>${p.client || "Selected public work"}</dd></div><div><dt>Industry</dt><dd>${p.industry || p.category}</dd></div><div><dt>Deliverables</dt><dd>${p.deliverables || "Campaign imagery · Social assets"}</dd></div></dl></div></section><section class="case-gallery">${p.gallery.map((x,i)=>picture(x,`${p.title}, selected image ${i+1}`)).join("")}</section>${videos}<nav class="next-project"><p class="eyebrow">Continue exploring</p>${arrow("All selected work","/work/","giant-link")}</nav></article>`}); }

const notFound = shell({title:"Page not found",description:"The page you were looking for could not be found.",path:"/404.html",body:`<section class="page-hero"><p class="eyebrow reveal">404 · Wrong turn</p><h1 class="reveal">Nothing to see<br><em>here.</em></h1><p class="page-intro reveal">That page has moved, disappeared or never made it out of the edit. Head back to the work and keep looking.</p><div class="reveal" style="margin-top:2rem">${arrow("Return home","/","button light")}</div></section>`});
const pages = [["index.html",home],["404.html",notFound],["work/index.html",work],["services/index.html",servicesPage],["content-guidance/index.html",contentGuidance],["clients/index.html",clients],["about/index.html",about],["contact/index.html",contact],...projects.map(p=>[`work/${p.slug}/index.html`,caseStudy(p)])];

await rm("dist", { recursive: true, force: true });
await mkdir("dist", { recursive: true });
for (const [file, html] of pages) { const out=join("dist",file); await mkdir(dirname(out),{recursive:true}); await writeFile(out,html); }
await cp("public","dist",{recursive:true});
await mkdir("dist/portal", { recursive: true });
await cp("portal/index.html", "dist/portal/index.html");
await cp("portal/styles.css", "dist/portal/styles.css");
await bundle({
  entryPoints: ["portal/main.ts"],
  bundle: true,
  minify: true,
  sourcemap: false,
  platform: "browser",
  format: "iife",
  target: ["es2022"],
  outfile: "dist/portal/app.js",
  define: {
    __SUPABASE_URL__: JSON.stringify(process.env.SUPABASE_URL || ""),
    __SUPABASE_ANON_KEY__: JSON.stringify(process.env.SUPABASE_ANON_KEY || ""),
  },
});
const portalBundle = await readFile("dist/portal/app.js", "utf8");
await writeFile("dist/portal/app.js", portalBundle.replace(/[\t ]+$/gm, ""));
const urls = ["/","/work/","/clients/","/services/","/content-guidance/","/about/","/contact/",...projects.map(p=>`/work/${p.slug}/`)];
await writeFile("dist/sitemap.xml",`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(x=>`<url><loc>${site.url}${x}</loc></url>`).join("")}</urlset>`);
await writeFile("dist/robots.txt",`User-agent: *\nAllow: /\nSitemap: ${site.url}/sitemap.xml\n`);
console.log(`Built ${pages.length} pages into dist/`);
