import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

const site = {
  url: "https://masethecreative.co.uk",
  instagram: "https://instagram.com/masethecreative",
  name: "Mase the Creative",
};

const projects = [
  { slug: "people-with-presence", title: "People with presence", type: "People · Photography", category: "people", image: "/media/portrait-sun.webp", alt: "Portrait of a woman outdoors beneath a bright, cloud-filled sky.", summary: "Natural, character-led portraits that feel considered without feeling staged.", gallery: ["/media/woman-red.webp", "/media/man-dusk.webp"] },
  { slug: "hospitality-in-motion", title: "Hospitality in motion", type: "Hospitality · Social content", category: "hospitality", image: "/media/chef-doorway.webp", alt: "A chef in an apron smiling from the doorway of a restaurant.", summary: "Food, people and atmosphere shaped into a visual story customers can almost taste.", gallery: ["/media/food.webp", "/media/chef-prep.webp", "/media/restaurant.webp"] },
  { slug: "after-dark", title: "After dark", type: "Hospitality · Photography", category: "hospitality", image: "/media/cocktail.webp", alt: "A cocktail served in a coupe glass with a cherry garnish.", summary: "A warm, cinematic study of service, detail and the mood of an evening out.", gallery: ["/media/table-setting.webp", "/media/restaurant.webp"] },
  { slug: "story-in-frame", title: "A story in every frame", type: "Brand film · Campaign", category: "film", image: "/media/vintage-car.webp", alt: "A man in vintage formalwear standing beside a classic black car.", summary: "Narrative-led campaign imagery built to stop the scroll and leave a lasting impression.", gallery: ["/media/top-hat.webp", "/media/field-sunset.webp", "/media/christmas-card.webp"] },
];

const services = [
  ["01", "Monthly social content", "A reliable stream of photography, short-form video and ideas—planned, shot and edited without adding another job to your week."],
  ["02", "Photography", "Commercial, hospitality, people, product, event and lifestyle photography with an editorial eye."],
  ["03", "Video production", "Brand films, interviews, behind-the-scenes stories, event coverage and launch content made for every screen."],
  ["04", "Content strategy", "Repeatable formats, strong hooks and a practical plan for what to make, where to post and why it matters."],
  ["05", "Reels & TikTok", "Vertical films designed around attention, personality and stories people genuinely want to finish."],
  ["06", "Campaigns & launches", "Focused creative support for new menus, products, locations, events, seasons and big announcements."],
];

const icon = `<svg viewBox="0 0 22 22" aria-hidden="true"><path d="M4 11h13M12 5l6 6-6 6"/></svg>`;
const arrow = (label, href, cls = "text-link") => `<a class="${cls}" href="${href}"><span>${label}</span>${icon}</a>`;
const picture = (src, alt, cls = "") => `<img class="${cls}" src="${src}" alt="${alt}" loading="lazy" decoding="async">`;

function shell({ title, description, path, body, theme = "dark" }) {
  const canonical = `${site.url}${path === "/" ? "" : path}`;
  const nav = [["Work", "/work/"], ["Clients", "/clients/"], ["Services", "/services/"], ["About", "/about/"]];
  return `<!doctype html>
<html lang="en-GB" data-theme="${theme}">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${title} — Mase the Creative</title>
  <meta name="description" content="${description}"><link rel="canonical" href="${canonical}">
  <meta property="og:type" content="website"><meta property="og:site_name" content="Mase the Creative"><meta property="og:title" content="${title} — Mase the Creative"><meta property="og:description" content="${description}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${site.url}/media/chef-doorway.webp">
  <meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#0b0b0a">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css">
  <script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"ProfessionalService",name:site.name,url:site.url,sameAs:[site.instagram],founder:{"@type":"Person",name:"Mason Osborne"},areaServed:"United Kingdom"})}</script>
</head>
<body>
  <a class="skip" href="#main">Skip to content</a>
  <header class="site-header" data-header>
    <a class="brand" href="/" aria-label="Mase the Creative home"><img class="brand-logo" src="/brand/mase-logo.png" alt="Mase the Creative"></a>
    <nav class="desktop-nav" aria-label="Primary">${nav.map(([n,h]) => `<a href="${h}"${path.startsWith(h.replace(/\/$/,"")) ? ` aria-current="page"` : ""}>${n}</a>`).join("")}<a class="nav-cta" href="/contact/">Start a project</a></nav>
    <button class="menu-button" type="button" aria-expanded="false" aria-controls="mobile-menu"><span>Menu</span><i></i><i></i></button>
  </header>
  <div class="mobile-menu" id="mobile-menu" aria-hidden="true"><nav aria-label="Mobile">${nav.map(([n,h],i)=>`<a href="${h}"><small>0${i+1}</small>${n}</a>`).join("")}<a href="/contact/"><small>05</small>Start a project</a></nav><a href="${site.instagram}">Instagram ↗</a></div>
  <main id="main">${body}</main>
  <footer class="site-footer">
    <div><p class="eyebrow">Ready when you are</p><h2>Make something<br><em>worth watching.</em></h2>${arrow("Start a project", "/contact/", "button light")}</div>
    <div class="footer-row"><a class="brand footer-brand" href="/" aria-label="Mase the Creative home"><img class="brand-logo" src="/brand/mase-logo.png" alt="Mase the Creative"></a><nav>${nav.map(([n,h])=>`<a href="${h}">${n}</a>`).join("")}<a href="/contact/">Contact</a></nav><div><a href="${site.instagram}">Instagram ↗</a><p>Trading as Edge Media Creative</p></div></div>
    <div class="footer-base"><span>© ${new Date().getFullYear()} Mase the Creative</span><span>Photography · Film · Social</span></div>
  </footer>
  <aside class="chatbot" data-chatbot>
    <button class="chatbot-launch" type="button" aria-label="Ask Mase" aria-expanded="false" aria-controls="mase-chat"><span class="chatbot-pulse"></span><span>Ask Mase</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 6.5h14v9H9l-4 3v-12Z"/></svg></button>
    <section class="chatbot-panel" id="mase-chat" aria-label="Ask Mase assistant" aria-hidden="true">
      <header class="chatbot-header"><div><span class="chatbot-avatar">M</span><p><strong>Ask Mase</strong><small>Business assistant · replies instantly</small></p></div><button type="button" class="chatbot-close" aria-label="Close assistant">×</button></header>
      <div class="chatbot-messages" role="log" aria-live="polite" aria-relevant="additions"><div class="chat-message assistant"><p>Hi — I can answer questions about Mase the Creative or help shape your enquiry.</p><p>What are you trying to achieve?</p></div></div>
      <div class="chatbot-quick" aria-label="Suggested replies"><button type="button">I need regular content</button><button type="button">I have a one-off project</button><button type="button">What do you offer?</button></div>
      <form class="chatbot-form"><label class="sr-only" for="chatbot-input">Message</label><textarea id="chatbot-input" name="message" rows="1" maxlength="1200" placeholder="Type your message…" required></textarea><button type="submit" aria-label="Send message">${icon}</button></form>
      <p class="chatbot-disclosure">AI assistant using verified Mase the Creative information. It cannot confirm prices or availability.</p>
    </section>
  </aside>
  <div class="cursor-dot" aria-hidden="true"></div><script src="/main.js" defer></script><script src="/chatbot.js" defer></script>
</body></html>`;
}

function projectCard(p, i) { return `<article class="project-card reveal" data-category="${p.category}"><a href="/work/${p.slug}/"><div class="project-media">${picture(p.image,p.alt)}<span class="project-index">0${i+1}</span><span class="view-pill">View project ${icon}</span></div><div class="project-meta"><h3>${p.title}</h3><p>${p.type}</p></div></a></article>`; }

const home = shell({title:"Content made to be noticed",description:"Photography, film and social content for businesses ready to get noticed.",path:"/",body:`
<section class="hero">
  <div class="hero-bg">${picture("/media/chef-doorway.webp","A chef smiling in the doorway of a restaurant.","hero-image")}</div><div class="hero-shade"></div>
  <div class="hero-copy"><p class="eyebrow reveal">Photography · Film · Social</p><h1><span class="reveal">Your business</span><span class="reveal"><em>deserves</em> to be seen.</span></h1><div class="hero-bottom reveal"><p>Content made for the way people discover businesses now.</p>${arrow("Explore the work","/work/","button light")}</div></div>
  <div class="scroll-note">Scroll to discover <span>↓</span></div>
</section>
<section class="manifesto section-pad"><p class="eyebrow reveal">The feed has changed</p><h2 class="statement reveal">You are no longer posting<br>only to <span>your followers.</span></h2><div class="manifesto-grid"><p class="lead reveal">Social media is becoming <em>interest media.</em></p><div class="reveal"><p>The right piece of content can reach the right person before they have ever heard of your business. Platforms find audiences through interest, behaviour and relevance—not just a follower count.</p><p>That creates a bigger opening for businesses with something real to show.</p>${arrow("Why content matters","/services/")}</div></div></section>
<section class="selected-work section-pad"><div class="section-head reveal"><div><p class="eyebrow">Selected work</p><h2>Proof, not promises.</h2></div>${arrow("View every project","/work/")}</div><div class="project-grid">${projects.map(projectCard).join("")}</div></section>
<section class="attention section-pad"><div class="attention-sticky"><p class="eyebrow">Built for attention</p><h2>Good content earns<br>a second look.</h2></div><div class="attention-list">${[["01","Familiarity","Show up consistently enough to become recognisable."],["02","Trust","Let people see the faces, craft and thinking behind the business."],["03","Consideration","Give a future customer a reason to remember you when it matters."],["04","Momentum","Build a useful library for social, your website and every campaign after it."]].map(x=>`<article class="reveal"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("")}</div></section>
<section class="services-preview section-pad"><div class="section-head reveal"><div><p class="eyebrow">What I do</p><h2>One creative partner.<br>Every useful format.</h2></div><p>From the first idea to the final export, the work stays connected to what your business actually needs.</p></div><div class="service-lines">${services.slice(0,5).map(s=>`<a href="/services/" class="reveal"><span>${s[0]}</span><h3>${s[1]}</h3>${icon}</a>`).join("")}</div></section>
<section class="about-split"><div class="about-photo reveal">${picture("/media/mason.webp","Mason Osborne, founder of Mase the Creative.")}</div><div class="about-copy section-pad reveal"><p class="eyebrow">Behind the camera</p><h2>Creative instinct.<br><em>Business sense.</em></h2><p>I’m Mason—the person planning, shooting and editing the work. A background in retail and business means I understand that content cannot just look good. It has to be useful, clear and worth the time it takes to make.</p>${arrow("Meet Mason","/about/")}</div></section>`});

const work = shell({title:"Selected work",description:"A selection of photography, hospitality, people and campaign work by Mase the Creative.",path:"/work/",theme:"light",body:`<section class="page-hero light"><p class="eyebrow reveal">Selected work · 2026</p><h1 class="reveal">Made to be<br><em>remembered.</em></h1><p class="page-intro reveal">A selection of people, places, products and moments—captured with enough character to stop somebody mid-scroll.</p></section><section class="work-page section-pad"><div class="filters reveal" aria-label="Filter work"><button class="active" data-filter="all">All</button><button data-filter="hospitality">Hospitality</button><button data-filter="people">People</button><button data-filter="film">Film & campaign</button></div><div class="project-grid work-grid">${projects.map(projectCard).join("")}</div><div class="gallery-strip reveal">${["/media/project-01.webp","/media/project-02.webp","/media/project-03.webp"].map((x,i)=>picture(x,`Additional portfolio image ${i+1}`)).join("")}</div></section>`});

const servicesPage = shell({title:"Services",description:"Monthly social content, photography, video production and content strategy for modern businesses.",path:"/services/",body:`<section class="page-hero"><p class="eyebrow reveal">Services</p><h1 class="reveal">Everything you need<br>to <em>show up well.</em></h1><p class="page-intro reveal">Not a menu of disconnected deliverables. A joined-up creative process built around what your business needs people to notice.</p></section><section class="service-detail section-pad">${services.map(s=>`<article class="reveal"><span>${s[0]}</span><h2>${s[1]}</h2><p>${s[2]}</p>${arrow("Discuss this service","/contact/")}</article>`).join("")}</section><section class="process section-pad"><p class="eyebrow reveal">A simple process</p><h2 class="reveal">Less friction.<br>Better work.</h2><ol>${["Understand the business","Develop the ideas","Plan the shoot","Create the content","Edit and deliver","Review and improve"].map((x,i)=>`<li class="reveal"><span>0${i+1}</span><p>${x}</p></li>`).join("")}</ol></section>`});

const clients = shell({title:"Clients",description:"Creative support for hospitality, retail, automotive, professional services, events and lifestyle businesses.",path:"/clients/",theme:"light",body:`<section class="page-hero light"><p class="eyebrow reveal">Clients & collaborations</p><h1 class="reveal">Good work starts<br>with <em>knowing the business.</em></h1><p class="page-intro reveal">Mase the Creative works across hospitality, retail, automotive, professional services, events and lifestyle—adapting the format while keeping the story human.</p></section><section class="industry-list section-pad">${[["01","Hospitality","Food, atmosphere, teams and the reasons people choose to visit."],["02","Retail","Products with context, character and a point of view."],["03","Automotive & engineering","Craft, detail and capability captured with energy."],["04","Professional services","Clear, human content that puts expertise into view."],["05","Events & lifestyle","Real moments, thoughtful coverage and assets that keep working afterwards."]].map(x=>`<article class="reveal"><span>${x[0]}</span><h2>${x[1]}</h2><p>${x[2]}</p></article>`).join("")}</section><section class="relationship section-pad"><div class="reveal"><p class="eyebrow">Ongoing</p><h2>Keep showing up.</h2><p>Monthly content gives your business a consistent visual language and a useful bank of new material—without starting from zero every time you post.</p></div><div class="reveal"><p class="eyebrow">One-off</p><h2>Make the moment count.</h2><p>A focused shoot for a launch, campaign, event, new menu or story that needs to land properly.</p></div></section>`});

const about = shell({title:"About Mason",description:"Meet Mason Osborne, the photographer, filmmaker and creative partner behind Mase the Creative.",path:"/about/",body:`<section class="page-hero about-hero"><div><p class="eyebrow reveal">About Mason</p><h1 class="reveal">One person.<br><em>Fully invested.</em></h1><p class="page-intro reveal">No layers of account management. The person you speak to is the person thinking, planning, shooting and editing.</p></div>${picture("/media/mason.webp","Mason Osborne, founder of Mase the Creative.","reveal")}</section><section class="about-story section-pad"><div><p class="eyebrow reveal">The short version</p><h2 class="reveal">I make businesses look as good online as they are in real life.</h2></div><div class="story-copy reveal"><p>I’m Mason, the person behind Mase the Creative—a one-person production company making photography, films and social content for businesses with something worth showing.</p><p>My background spans retail, running a business, social media, photography and filmmaking. That mix matters. I know the creative has to earn attention, but I also know it has to fit the reality of a working business.</p><p>I keep the process direct: understand what makes the business interesting, find the idea, then turn up and make the work. No twelve-meeting agency theatre.</p></div></section><section class="beliefs section-pad"><p class="eyebrow reveal">The approach</p>${[["01","Useful beats ornamental.","Looking good is the start. Every shoot should give the business material it can actually use."],["02","Personality is an advantage.","The people, details and oddities behind a business are usually what make it memorable."],["03","Consistency compounds.","One strong film helps. A clear body of work, built over time, changes how a business is seen."]].map(x=>`<article class="reveal"><span>${x[0]}</span><h2>${x[1]}</h2><p>${x[2]}</p></article>`).join("")}</section>`});

const contact = shell({title:"Start a project",description:"Tell Mase the Creative about your photography, film or social content project.",path:"/contact/",body:`<section class="contact-page"><div class="contact-intro"><p class="eyebrow reveal">Start a project</p><h1 class="reveal">Let’s make<br>something <em>useful.</em></h1><p class="reveal">Tell me what you are building, launching or trying to get noticed. A rough idea is plenty.</p><div class="contact-social reveal"><span>Prefer a direct message?</span><a href="${site.instagram}">Instagram ↗</a></div></div><form class="project-form" novalidate><div class="field-row"><label><span>Your name *</span><input name="name" autocomplete="name" required></label><label><span>Business name *</span><input name="business" autocomplete="organization" required></label></div><div class="field-row"><label><span>Email *</span><input type="email" name="email" autocomplete="email" required></label><label><span>Phone <small>optional</small></span><input type="tel" name="phone" autocomplete="tel"></label></div><label><span>What do you need? *</span><select name="project" required><option value="">Choose a project type</option><option>Monthly social content</option><option>Photography</option><option>Video production</option><option>Event coverage</option><option>Campaign or launch</option><option>One-off content day</option><option>Something else</option></select></label><div class="field-row"><label><span>Approximate budget *</span><select name="budget" required><option value="">Choose a range</option><option>Under £1,000</option><option>£1,000–£2,500</option><option>£2,500–£5,000</option><option>£5,000+</option><option>Not sure yet</option></select></label><label><span>Preferred start</span><input type="date" name="start"></label></div><label><span>Tell me about it *</span><textarea name="message" rows="5" required placeholder="What are you working on, and what would a good outcome look like?"></textarea></label><label class="honeypot" aria-hidden="true">Company website<input name="company_website" tabindex="-1" autocomplete="off"></label><button class="button light submit-button" type="submit"><span>Prepare enquiry</span>${icon}</button><p class="form-note">Your details stay on this device. Preparing the enquiry copies it so you can send it directly.</p><div class="form-status" role="status" aria-live="polite"></div></form></section>`});

function caseStudy(p) { return shell({title:p.title,description:p.summary,path:`/work/${p.slug}/`,body:`<article class="case-study"><header class="case-hero"><div><p class="eyebrow reveal">${p.type}</p><h1 class="reveal">${p.title}</h1><p class="reveal">${p.summary}</p></div>${picture(p.image,p.alt,"reveal")}</header><section class="case-overview section-pad"><div><p class="eyebrow">The approach</p><h2>Start with the feeling.<br>Build every frame around it.</h2></div><div><p>The strongest content does more than document what happened. It gives the viewer a reason to stay, notice a detail and understand the character behind the business.</p><dl><div><dt>Format</dt><dd>${p.type}</dd></div><div><dt>Deliverables</dt><dd>Campaign imagery · Social assets</dd></div><div><dt>Availability</dt><dd>Selected public work</dd></div></dl></div></section><section class="case-gallery">${p.gallery.map((x,i)=>picture(x,`${p.title}, selected image ${i+1}`)).join("")}</section><nav class="next-project"><p class="eyebrow">Continue exploring</p>${arrow("All selected work","/work/","giant-link")}</nav></article>`}); }

const notFound = shell({title:"Page not found",description:"The page you were looking for could not be found.",path:"/404.html",body:`<section class="page-hero"><p class="eyebrow reveal">404 · Wrong turn</p><h1 class="reveal">Nothing to see<br><em>here.</em></h1><p class="page-intro reveal">That page has moved, disappeared or never made it out of the edit. Head back to the work and keep looking.</p><div class="reveal" style="margin-top:2rem">${arrow("Return home","/","button light")}</div></section>`});
const pages = [["index.html",home],["404.html",notFound],["work/index.html",work],["services/index.html",servicesPage],["clients/index.html",clients],["about/index.html",about],["contact/index.html",contact],...projects.map(p=>[`work/${p.slug}/index.html`,caseStudy(p)])];

await rm("dist", { recursive: true, force: true });
await mkdir("dist", { recursive: true });
for (const [file, html] of pages) { const out=join("dist",file); await mkdir(dirname(out),{recursive:true}); await writeFile(out,html); }
await cp("public","dist",{recursive:true});
const urls = ["/","/work/","/clients/","/services/","/about/","/contact/",...projects.map(p=>`/work/${p.slug}/`)];
await writeFile("dist/sitemap.xml",`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(x=>`<url><loc>${site.url}${x}</loc></url>`).join("")}</urlset>`);
await writeFile("dist/robots.txt",`User-agent: *\nAllow: /\nSitemap: ${site.url}/sitemap.xml\n`);
console.log(`Built ${pages.length} pages into dist/`);
